name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn lint:fix
      - run: yarn pretty:fix
      - run: yarn build
      - run: yarn test

      - name: 'Verify lint/pretty/build made no changes'
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
              echo ----------------------------------------
              echo git status
              echo ----------------------------------------
              git status
              echo ----------------------------------------
              echo git diff
              echo ----------------------------------------
              git diff
              echo ----------------------------------------
              echo Troubleshooting
              echo ----------------------------------------
              echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && yarn install --frozen-lockfile && yarn lint:fix && yarn pretty:fix && yarn build && yarn test"
              exit 1
          fi
